import type { Contact, ContactFilter, OrgMember, OrgNode, PersonMail } from "@/types/contacts";

// Mock data and helpers for the Contacts and Org Chart pages.
const PALETTE = [
  { bg: "#E4EAFE", fg: "#2B4BF2" },
  { bg: "#F0EBE1", fg: "#6F6044" },
  { bg: "#E9F3EC", fg: "#267547" },
  { bg: "#FBEAE8", fg: "#AA3831" },
  { bg: "#EDEBF7", fg: "#6B5CA8" },
  { bg: "#E8F1F5", fg: "#306982" },
];

// Cycles through PALETTE so avatar colors repeat predictably once the list is exhausted.
function paletteAt(i: number) {
  return PALETTE[i % PALETTE.length];
}

function initialsOf(name: string) {
  return name.slice(0, 1);
}

export const CONTACT_GROUPS: ContactFilter[] = ["all", "starred", "external", "purchasing"];

export const MY_CONTACTS: Contact[] = [
  {
    id: "c1",
    name: "서지훈",
    email: "jihoon.seo@hanbit-tech.kr",
    company: "한빛테크",
    title: "구매팀 과장",
    phone: "02-2345-6001",
    mobile: "010-3456-7001",
    memo: "",
    group: "purchasing",
    starred: true,
    ...paletteAt(0),
    initials: initialsOf("서지훈"),
  },
  {
    id: "c2",
    name: "Emma Rossi",
    email: "emma.rossi@northwind.io",
    company: "Northwind",
    title: "Partnerships Lead",
    phone: "+39 06 1234 5678",
    mobile: "+39 345 678 9012",
    memo: "",
    group: "external",
    starred: true,
    ...paletteAt(1),
    initials: initialsOf("Emma Rossi"),
  },
  {
    id: "c3",
    name: "나윤성",
    email: "yunsung.na@gxsoft.co.kr",
    company: "GXSOFT",
    title: "재무팀 대리",
    phone: "02-1234-5602",
    mobile: "010-2345-6702",
    memo: "",
    group: "personal",
    starred: false,
    ...paletteAt(2),
    initials: initialsOf("나윤성"),
  },
  {
    id: "c4",
    name: "장미래",
    email: "mirae.jang@partner-corp.com",
    company: "파트너코퍼레이션",
    title: "영업본부장",
    phone: "02-3456-7003",
    mobile: "010-4567-8003",
    memo: "",
    group: "external",
    starred: false,
    ...paletteAt(3),
    initials: initialsOf("장미래"),
  },
  {
    id: "c5",
    name: "Kenji Watanabe",
    email: "kenji.watanabe@sakura-consulting.jp",
    company: "Sakura Consulting",
    title: "Senior Advisor",
    phone: "+81 3 1234 5678",
    mobile: "+81 90 1234 5678",
    memo: "",
    group: "advisor",
    starred: false,
    ...paletteAt(4),
    initials: initialsOf("Kenji Watanabe"),
  },
  {
    id: "c6",
    name: "황도윤",
    email: "doyun.hwang@gxsoft.co.kr",
    company: "GXSOFT",
    title: "인사팀 사원",
    phone: "02-1234-5606",
    mobile: "010-2345-6706",
    memo: "",
    group: "personal",
    starred: false,
    ...paletteAt(5),
    initials: initialsOf("황도윤"),
  },
  {
    id: "c7",
    name: "최민서",
    email: "minseo.choi@hanbit-tech.kr",
    company: "한빛테크",
    title: "구매팀 사원",
    phone: "02-2345-6007",
    mobile: "010-3456-7007",
    memo: "",
    group: "purchasing",
    starred: false,
    ...paletteAt(0),
    initials: initialsOf("최민서"),
  },
];

export const ORG_TREE: OrgNode[] = [
  { id: "org-root", name: "GXSOFT", count: 214, depth: 0, parentId: null },
  { id: "org-mgmt", name: "경영기획본부", count: 38, depth: 1, parentId: "org-root" },
  { id: "org-strategy", name: "전략기획팀", count: 14, depth: 2, parentId: "org-mgmt" },
  { id: "org-finance", name: "재무팀", count: 12, depth: 2, parentId: "org-mgmt" },
  { id: "org-dev", name: "개발본부", count: 96, depth: 1, parentId: "org-root" },
  { id: "org-backend", name: "백엔드팀", count: 22, depth: 2, parentId: "org-dev" },
  { id: "org-frontend", name: "프론트엔드팀", count: 18, depth: 2, parentId: "org-dev" },
  { id: "org-hr", name: "인사팀", count: 16, depth: 1, parentId: "org-root" },
];

export const ORG_MEMBERS: OrgMember[] = [
  {
    id: "m1",
    teamId: "org-strategy",
    name: "한지우",
    title: "경영기획본부 전략기획팀 · 차장",
    email: "jiwoo.han@gxsoft.co.kr",
    phone: "02-1234-5678",
    mobile: "010-2345-6789",
    joined: "2019-03-04",
    approvalLine: "directorCeo",
    presence: "working",
    ...paletteAt(0),
    initials: initialsOf("한지우"),
  },
  {
    id: "m2",
    teamId: "org-strategy",
    name: "오세린",
    title: "전략기획팀 · 대리",
    email: "serin.oh@gxsoft.co.kr",
    phone: "02-1234-5679",
    mobile: "010-2345-6790",
    joined: "2022-07-11",
    approvalLine: "leadDirector",
    presence: "away",
    ...paletteAt(1),
    initials: initialsOf("오세린"),
  },
  {
    id: "m3",
    teamId: "org-strategy",
    name: "강태윤",
    title: "전략기획팀 · 사원",
    email: "taeyun.kang@gxsoft.co.kr",
    phone: "02-1234-5680",
    mobile: "010-2345-6791",
    joined: "2024-01-08",
    approvalLine: "leadDirector",
    presence: "working",
    ...paletteAt(2),
    initials: initialsOf("강태윤"),
  },
  {
    id: "m4",
    teamId: "org-strategy",
    name: "문지호",
    title: "전략기획팀 · 팀장",
    email: "jiho.moon@gxsoft.co.kr",
    phone: "02-1234-5681",
    mobile: "010-2345-6792",
    joined: "2016-09-21",
    approvalLine: "directorCeo",
    presence: "offline",
    ...paletteAt(3),
    initials: initialsOf("문지호"),
  },
  {
    id: "m5",
    teamId: "org-strategy",
    name: "배수아",
    title: "전략기획팀 · 주임",
    email: "sua.bae@gxsoft.co.kr",
    phone: "02-1234-5682",
    mobile: "010-2345-6793",
    joined: "2023-05-15",
    approvalLine: "leadDirector",
    presence: "working",
    ...paletteAt(4),
    initials: initialsOf("배수아"),
  },
  {
    id: "m6",
    teamId: "org-strategy",
    name: "신유진",
    title: "전략기획팀 · 대리",
    email: "yujin.shin@gxsoft.co.kr",
    phone: "02-1234-5683",
    mobile: "010-2345-6794",
    joined: "2021-11-02",
    approvalLine: "leadDirector",
    presence: "working",
    ...paletteAt(5),
    initials: initialsOf("신유진"),
  },
];

export const PERSON_MAILS: Record<string, PersonMail[]> = {
  m1: [
    { subject: "9월 정기 워크샵 일정 안내", date: "2026-09-07" },
    { subject: "예산 리뷰 회의록 공유", date: "2026-09-03" },
  ],
};
