import type { Email, Folder } from "@/types/mail";
import { CURRENT_USER } from "@/lib/current-user";

// Seed data for the main inbox: folder list and the initial set of emails.
// MailProvider (context/mail-context.tsx) copies this into React state, so
// edits here only affect what a fresh page load starts with.
export const FOLDERS: Folder[] = [
  { id: "inbox" },
  { id: "drafts" },
  { id: "sent" },
  { id: "archive" },
  { id: "spam" },
  { id: "trash" },
];

export const MOCK_EMAILS: Email[] = [
  {
    id: "invite-1",
    folder: "inbox",
    from: { name: "최민서", email: "minseo.choi@gxsoft.co.kr" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "[초대] 아틀라스 3차 스프린트 리뷰 · 인프라 증설 안건 포함",
    preview: "다음 스프린트 리뷰에 인프라 증설 안건을 함께 다루려고 합니다...",
    body: [
      "안녕하세요, 최민서입니다.",
      "다음 스프린트 리뷰에 인프라 증설 안건을 함께 다루려고 합니다. 지난 회의에서 논의된 GPU 노드 증설 건에 대한 최종 검토도 함께 진행할 예정이니 관련 자료를 미리 검토 부탁드립니다.",
    ],
    receivedAt: "2026-09-07T11:04:00+09:00",
    unread: true,
    starred: false,
    invite: {
      startsAt: "2026-09-11T14:00:00+09:00",
      endsAt: "2026-09-11T15:30:00+09:00",
      where: "본사 12층 아틀라스룸 · Meet 링크 포함",
      organizer: "최민서 (플랫폼개발팀)",
      recurrence: "격주 금요일 · 12월 19일까지",
      conflict: "재무팀 정기 회의 (14:00–15:00)",
      attendees: [
        { name: "최민서", team: "플랫폼개발팀", state: "accept", isHost: true },
        { name: "한지우", team: "전략기획팀 · 나", state: "tentative" },
        { name: "박서준", team: "인프라팀", state: "accept" },
        { name: "이수민", team: "재무팀", state: "accept" },
        { name: "강태윤", team: "QA팀", state: "accept" },
        { name: "윤재호", team: "영업팀", state: "decline" },
        { name: "오세린", team: "대표이사실", state: "noResponse" },
        { name: "배수아", team: "브랜드팀", state: "noResponse" },
        { name: "Alex Meyer", team: "Global Partnerships", state: "noResponse" },
      ],
    },
  },
  {
    id: "1",
    folder: "inbox",
    from: { name: "김민준 (GXSOFT 인사팀)", email: "hr@gxsoft.co.kr" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "9월 정기 워크샵 일정 안내",
    preview: "안녕하세요. 이번 달 정기 워크샵 일정을 다음과 같이 안내드립니다...",
    body: [
      "안녕하세요, GXSOFT 인사팀입니다.",
      "이번 달 정기 워크샵 일정을 다음과 같이 안내드립니다.",
      "일시: 2026년 9월 18일(금) 오후 2시\n장소: 본사 3층 대강당",
      "참석 여부는 9월 12일까지 회신 부탁드립니다.",
      "감사합니다.",
    ],
    receivedAt: "2026-09-07T08:12:00+09:00",
    unread: true,
    starred: false,
  },
  {
    id: "2",
    folder: "inbox",
    from: { name: "박서연", email: "seoyeon.park@partner-corp.com" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "웹메일 프로젝트 킥오프 회의록 공유드립니다",
    preview: "어제 킥오프 회의에서 논의된 내용을 정리해서 공유드립니다...",
    body: [
      "안녕하세요, 박서연입니다.",
      "어제 킥오프 회의에서 논의된 내용을 정리해서 공유드립니다.",
      "1. 레이아웃은 3단 구성(사이드바 / 목록 / 본문)으로 진행\n2. 테마 커스터마이징 기능 우선 개발\n3. 다음 리뷰는 다음 주 화요일",
      "추가로 확인이 필요하시면 언제든 연락 주세요.",
    ],
    receivedAt: "2026-09-06T17:45:00+09:00",
    unread: true,
    starred: true,
  },
  {
    id: "3",
    folder: "inbox",
    from: { name: "GitHub", email: "notifications@github.com" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "[gxsoft/webmail] 새 Pull Request가 열렸습니다",
    preview: "feature/theme-customizer 브랜치에서 PR #12가 생성되었습니다...",
    body: [
      "feature/theme-customizer 브랜치에서 PR #12가 생성되었습니다.",
      "변경 사항: 테마 커스터마이저 색상/폰트 패널 추가",
      "리뷰어로 지정되셨습니다. 확인 부탁드립니다.",
    ],
    receivedAt: "2026-09-06T11:20:00+09:00",
    unread: false,
    starred: false,
  },
  {
    id: "4",
    folder: "inbox",
    from: { name: "이준호", email: "junho.lee@gxsoft.co.kr" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "다음 주 배포 일정 확인 부탁드립니다",
    preview: "다음 주 화요일 오전에 스테이징 배포를 진행하려고 합니다...",
    body: [
      "다음 주 화요일 오전에 스테이징 배포를 진행하려고 합니다.",
      "영향 범위와 롤백 계획을 간단히 정리해서 회신 부탁드립니다.",
    ],
    receivedAt: "2026-09-05T14:02:00+09:00",
    unread: false,
    starred: true,
  },
  {
    id: "5",
    folder: "inbox",
    from: { name: "Vercel", email: "no-reply@vercel.com" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "배포가 완료되었습니다: webmail-preview",
    preview: "프로젝트 webmail의 새 배포가 성공적으로 완료되었습니다...",
    body: [
      "프로젝트 webmail의 새 배포가 성공적으로 완료되었습니다.",
      "미리보기 URL에서 변경 사항을 확인하실 수 있습니다.",
    ],
    receivedAt: "2026-09-04T09:30:00+09:00",
    unread: false,
    starred: false,
  },
  {
    id: "6",
    folder: "sent",
    from: CURRENT_USER,
    to: ["seoyeon.park@partner-corp.com"],
    subject: "RE: 웹메일 프로젝트 킥오프 회의록 공유드립니다",
    preview: "회의록 잘 받았습니다. 몇 가지 추가 의견 전달드립니다...",
    body: [
      "회의록 잘 받았습니다.",
      "몇 가지 추가 의견 전달드립니다. 사이드바 위치를 커스터마이징 옵션에 포함해주시면 좋을 것 같습니다.",
    ],
    receivedAt: "2026-09-06T18:10:00+09:00",
    unread: false,
    starred: false,
  },
  {
    id: "7",
    folder: "drafts",
    from: CURRENT_USER,
    to: ["team@gxsoft.co.kr"],
    subject: "(작성 중) 9월 스프린트 회고",
    preview: "이번 스프린트 회고 초안입니다. 아직 정리 중입니다...",
    body: ["이번 스프린트 회고 초안입니다.", "아직 정리 중입니다."],
    receivedAt: "2026-09-05T16:40:00+09:00",
    unread: false,
    starred: false,
  },
  {
    id: "8",
    folder: "trash",
    from: { name: "마케팅 뉴스레터", email: "news@example-marketing.com" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "9월 할인 프로모션 안내",
    preview: "지금 바로 확인하세요! 이번 달 특별 할인 혜택...",
    body: ["지금 바로 확인하세요!", "이번 달 특별 할인 혜택을 놓치지 마세요."],
    receivedAt: "2026-09-03T10:00:00+09:00",
    unread: false,
    starred: false,
  },
  {
    id: "9",
    folder: "archive",
    from: { name: "GXSOFT 재무팀", email: "finance@gxsoft.co.kr" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "8월 법인카드 사용 내역 보관",
    preview: "확인 완료된 8월 법인카드 사용 내역을 보관합니다.",
    body: ["확인 완료된 8월 법인카드 사용 내역입니다.", "필요할 때 보관함에서 다시 확인할 수 있습니다."],
    receivedAt: "2026-09-02T15:25:00+09:00",
    unread: false,
    starred: false,
  },
  {
    id: "10",
    folder: "spam",
    from: { name: "서비스 안내", email: "offers@unknown-example.net" },
    to: ["whitecalvin@gxsoft.co.kr"],
    subject: "계정 용량을 지금 무료로 늘리세요",
    preview: "외부 발신자가 보낸 의심스러운 홍보 메일입니다.",
    body: ["외부 발신자가 보낸 의심스러운 홍보 메일입니다.", "링크를 열기 전에 발신자를 확인하세요."],
    receivedAt: "2026-09-01T07:40:00+09:00",
    unread: true,
    starred: false,
  },
];
