"use client";

import { useRef, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { Plus, Trash2 } from "lucide-react";
import { getPathname, usePathname } from "@/i18n/navigation";
import { localeNames, locales, type Locale } from "@/i18n/routing";
import { useSettings } from "@/context/settings-context";
import { useTheme } from "@/context/theme-context";
import { useWorkspaceSidebar } from "@/context/workspace-sidebar-context";
import { useToast } from "@/context/toast-context";
import { DEFAULT_USER_SETTINGS } from "@/lib/user-settings";
import { THEME_PRESETS } from "@/lib/theme-presets";
import type { SignatureSetting } from "@/types/user-settings";
import { Button } from "@/components/ui/Button";
import { Dropdown, type DropdownOption } from "@/components/ui/Dropdown";
import { Input } from "@/components/ui/Input";
import { SegmentedControl } from "@/components/ui/SegmentedControl";
import { Textarea } from "@/components/ui/Textarea";
import { Modal } from "@/components/overlay/Modal";
import { ConfirmDialog } from "@/components/overlay/ConfirmDialog";
import { SettingsPageIntro, SettingsPanel, SettingsSaveBar, SettingRow, SwitchRow } from "./SettingsPrimitives";

function Select({ value, onChange, options, label }: { value: string; onChange: (value: string) => void; options: DropdownOption[]; label: string }) {
  return <Dropdown value={value} onChange={onChange} options={options} variant="form" label={label} />;
}

export function LocaleSettingsView() {
  const t = useTranslations("settingsSystem");
  const locale = useLocale() as Locale;
  const pathname = usePathname();
  const { draft, updateSection, replaceSection, hydrated, save } = useSettings();
  const current = draft.locale;
  const changeLocale = (next: string) => {
    if (!locales.includes(next as Locale) || next === locale) return;
    save();
    const localized = getPathname({ href: pathname, locale: next as Locale, forcePrefix: true });
    window.location.replace(`${localized}${window.location.search}${window.location.hash}`);
  };
  const preview = hydrated ? new Intl.DateTimeFormat(locale, { dateStyle: current.dateFormat === "long" ? "full" : current.dateFormat === "iso" ? "short" : "medium", timeStyle: "short", hour12: current.timeFormat === "12", timeZone: current.timezone }).format(new Date("2026-09-13T09:30:00+09:00")) : "—";
  return <><SettingsPageIntro title={t("nav.locale")} description={t("descriptions.locale")} /><SettingsPanel title={t("sections.languageRegion")}>
    <SettingRow title={t("fields.displayLanguage")}><Select label={t("fields.displayLanguage")} value={locale} onChange={changeLocale} options={locales.map((value) => ({ value, label: localeNames[value] }))} /></SettingRow>
    <SettingRow title={t("fields.timezone")}><Select label={t("fields.timezone")} value={current.timezone} onChange={(timezone) => updateSection("locale", { timezone })} options={["Asia/Seoul","Asia/Tokyo","Asia/Shanghai","Europe/London","America/New_York","America/Los_Angeles"].map((value) => ({ value, label: t(`options.timezones.${value.replaceAll("/", "_")}`) }))} /></SettingRow>
    <SettingRow title={t("fields.dateFormat")}><SegmentedControl label={t("fields.dateFormat")} value={current.dateFormat} onChange={(dateFormat) => updateSection("locale", { dateFormat })} options={["locale","iso","long"].map((value) => ({ value: value as typeof current.dateFormat, label: t(`options.dateFormat.${value}`) }))} /></SettingRow>
    <SettingRow title={t("fields.timeFormat")}><SegmentedControl label={t("fields.timeFormat")} value={current.timeFormat} onChange={(timeFormat) => updateSection("locale", { timeFormat })} options={[{ value: "12" as const, label: t("options.timeFormat.12") }, { value: "24" as const, label: t("options.timeFormat.24") }]} /></SettingRow>
    <SettingRow title={t("fields.weekStart")}><SegmentedControl label={t("fields.weekStart")} value={current.weekStart} onChange={(weekStart) => updateSection("locale", { weekStart })} options={["sunday","monday"].map((value) => ({ value: value as typeof current.weekStart, label: t(`options.weekStart.${value}`) }))} /></SettingRow>
    <div className="rounded-(--radius-app) bg-(--surface-muted) p-4"><p className="text-xs font-semibold text-(--text-muted)">{t("common.preview")}</p><p className="mt-1 text-sm font-medium">{preview}</p></div>
  </SettingsPanel><SettingsSaveBar onReset={() => replaceSection("locale", structuredClone(DEFAULT_USER_SETTINGS.locale))} /></>;
}

export function ThemeSettingsView() {
  const t = useTranslations("settingsSystem");
  const { draft, updateDraft, publish, resetToDefaults, closeCustomizer, isDirty } = useTheme();
  const { collapsed, toggleCollapsed } = useWorkspaceSidebar();
  const [desiredCollapsed, setDesiredCollapsed] = useState(collapsed);
  const resetButtonRef = useRef<HTMLButtonElement>(null);
  const toast = useToast();
  const hasChanges = isDirty || desiredCollapsed !== collapsed;
  return <><SettingsPageIntro title={t("nav.theme")} description={t("descriptions.theme")} /><SettingsPanel title={t("sections.themePreset")}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{THEME_PRESETS.map((preset) => { const selected = Object.entries(preset.settings).every(([key, value]) => draft[key as keyof typeof draft] === value); return <Button key={preset.id} aria-pressed={selected} onClick={() => updateDraft(preset.settings)} className={`min-h-24 flex-col items-start p-4 text-left ${selected ? "border-(--color-primary) bg-(--color-primary)/8" : "border-(--border-app)"}`}><span className="text-sm font-bold">{preset.label}</span><span className="mt-2 flex gap-2"><span className="size-5 rounded-full" style={{ background: preset.settings.primaryColor }} /><span className="size-5 rounded-full" style={{ background: preset.settings.accentColor }} /></span></Button>; })}</div></SettingsPanel>
    <SettingsPanel title={t("sections.appearance")}><SettingRow title={t("fields.colorScheme")}><SegmentedControl label={t("fields.colorScheme")} value={draft.colorScheme} onChange={(colorScheme) => updateDraft({ colorScheme })} options={["light","dark","system"].map((value) => ({ value: value as typeof draft.colorScheme, label: t(`options.colorScheme.${value}`) }))} /></SettingRow><SettingRow title={t("fields.density")}><SegmentedControl label={t("fields.density")} value={draft.density} onChange={(density) => updateDraft({ density })} options={["comfortable","compact"].map((value) => ({ value: value as typeof draft.density, label: t(`options.density.${value}`) }))} /></SettingRow><SettingRow title={t("fields.radius")}><SegmentedControl label={t("fields.radius")} value={draft.radius} onChange={(radius) => updateDraft({ radius })} options={["sharp","rounded","pill"].map((value) => ({ value: value as typeof draft.radius, label: t(`options.radius.${value}`) }))} /></SettingRow><SettingRow title={t("fields.sidebarPosition")}><SegmentedControl label={t("fields.sidebarPosition")} value={draft.sidebarPosition} onChange={(sidebarPosition) => updateDraft({ sidebarPosition })} options={["left","right"].map((value) => ({ value: value as typeof draft.sidebarPosition, label: t(`options.sidebarPosition.${value}`) }))} /></SettingRow><SwitchRow title={t("fields.sidebarCollapsed")} value={desiredCollapsed} onChange={setDesiredCollapsed} /></SettingsPanel>
    <div className="sticky bottom-0 -mx-4 mt-auto flex justify-end gap-2 border-t border-(--border-app) bg-(--surface-app)/95 px-4 py-3 backdrop-blur sm:-mx-7 sm:px-7"><Button ref={resetButtonRef} variant="ghost" size="sm" onClick={() => { resetToDefaults(); setDesiredCollapsed(false); }}>{t("common.reset")}</Button><Button variant="secondary" size="sm" disabled={!hasChanges} onClick={() => { closeCustomizer({ discard: true }); setDesiredCollapsed(collapsed); resetButtonRef.current?.focus(); }}>{t("common.cancel")}</Button><Button variant="primary" size="sm" disabled={!hasChanges} onClick={() => { if (desiredCollapsed !== collapsed) toggleCollapsed(); publish(); resetButtonRef.current?.focus(); toast.success(t("common.savedToast")); }}>{t("common.save")}</Button></div>
  </>;
}

export function AccessibilitySettingsView() {
  const t = useTranslations("settingsSystem");
  const { draft, updateSection, replaceSection } = useSettings();
  const value = draft.accessibility;
  return <><SettingsPageIntro title={t("nav.accessibility")} description={t("descriptions.accessibility")} /><SettingsPanel title={t("sections.readability")}><SettingRow title={t("fields.fontScale")}><SegmentedControl label={t("fields.fontScale")} value={value.fontScale} onChange={(fontScale) => updateSection("accessibility", { fontScale })} options={["90","100","110","125"].map((item) => ({ value: item as typeof value.fontScale, label: `${item}%` }))} /></SettingRow><SwitchRow title={t("fields.highContrast")} value={value.highContrast} onChange={(highContrast) => updateSection("accessibility", { highContrast })} /><SwitchRow title={t("fields.reduceMotion")} value={value.reduceMotion} onChange={(reduceMotion) => updateSection("accessibility", { reduceMotion })} /><SwitchRow title={t("fields.enhancedFocus")} value={value.enhancedFocus} onChange={(enhancedFocus) => updateSection("accessibility", { enhancedFocus })} /><SwitchRow title={t("fields.screenReaderDetails")} value={value.screenReaderDetails} onChange={(screenReaderDetails) => updateSection("accessibility", { screenReaderDetails })} /><SwitchRow title={t("fields.keyboardNavigation")} value={value.keyboardNavigation} onChange={(keyboardNavigation) => updateSection("accessibility", { keyboardNavigation })} /></SettingsPanel><SettingsSaveBar onReset={() => replaceSection("accessibility", structuredClone(DEFAULT_USER_SETTINGS.accessibility))} /></>;
}

export function SignatureSettingsViewV2() {
  const t = useTranslations("settingsSystem");
  const { draft, updateSection, replaceSection } = useSettings();
  const [editing, setEditing] = useState<SignatureSetting | "new" | null>(null);
  const [form, setForm] = useState({ name: "", content: "" });
  const [deleting, setDeleting] = useState<SignatureSetting | null>(null);
  const compose = draft.compose;
  const openEditor = (signature?: SignatureSetting) => { setEditing(signature ?? "new"); setForm(signature ? { name: signature.name, content: signature.content } : { name: "", content: "" }); };
  const saveSignature = () => { if (!form.name.trim() || !form.content.trim()) return; const next = editing === "new" ? [...compose.signatures, { id: `signature-${Date.now()}`, name: form.name.trim(), content: form.content.trim() }] : compose.signatures.map((item) => item.id === editing?.id ? { ...item, ...form } : item); updateSection("compose", { signatures: next }); setEditing(null); };
  return <><SettingsPageIntro title={t("nav.signature")} description={t("descriptions.signature")} actions={<Button size="sm" variant="primary" leadingIcon={<Plus size={15} />} onClick={() => openEditor()}>{t("actions.addSignature")}</Button>} /><SettingsPanel title={t("sections.senderDefaults")}><SettingRow title={t("fields.senderName")}><Input aria-label={t("fields.senderName")} value={compose.senderName} onChange={(event) => updateSection("compose", { senderName: event.target.value })} /></SettingRow><SettingRow title={t("fields.senderAddress")}><Select label={t("fields.senderAddress")} value={compose.senderAddress} onChange={(senderAddress) => updateSection("compose", { senderAddress })} options={[draft.account.primaryEmail, ...draft.account.aliases].map((value) => ({ value, label: value }))} /></SettingRow><SettingRow title={t("fields.defaultFont")}><Select label={t("fields.defaultFont")} value={compose.font} onChange={(font) => updateSection("compose", { font })} options={["sans","serif","mono"].map((value) => ({ value, label: t(`options.font.${value}`) }))} /></SettingRow><SettingRow title={t("fields.undoSend")}><Select label={t("fields.undoSend")} value={compose.undoSeconds} onChange={(undoSeconds) => updateSection("compose", { undoSeconds: undoSeconds as typeof compose.undoSeconds })} options={["0","5","10","20","30"].map((value) => ({ value, label: t("options.seconds", { value }) }))} /></SettingRow></SettingsPanel>
    <SettingsPanel title={t("sections.signatures")} description={t("descriptions.signatureList")}><SettingRow title={t("fields.defaultSignature")}><Select label={t("fields.defaultSignature")} value={compose.defaultSignatureId} onChange={(defaultSignatureId) => updateSection("compose", { defaultSignatureId })} options={compose.signatures.map((item) => ({ value: item.id, label: item.name }))} /></SettingRow><SwitchRow title={t("fields.signatureOnNew")} value={compose.signatureOnNew} onChange={(signatureOnNew) => updateSection("compose", { signatureOnNew })} /><SwitchRow title={t("fields.signatureOnReply")} value={compose.signatureOnReply} onChange={(signatureOnReply) => updateSection("compose", { signatureOnReply })} />{compose.signatures.map((signature) => <article key={signature.id} className="rounded-(--radius-app) border border-(--border-app) p-4"><div className="flex items-center gap-2"><h3 className="flex-1 text-sm font-semibold">{signature.name}</h3><Button size="sm" variant="ghost" onClick={() => openEditor(signature)}>{t("common.edit")}</Button><Button size="icon" variant="ghost" className="size-8 text-(--status-danger)" aria-label={t("common.delete")} onClick={() => setDeleting(signature)}><Trash2 size={15} /></Button></div><pre className="mt-2 whitespace-pre-wrap text-xs text-(--text-muted)">{signature.content}</pre></article>)}</SettingsPanel><SettingsSaveBar onReset={() => replaceSection("compose", structuredClone(DEFAULT_USER_SETTINGS.compose))} />
    {editing ? <Modal onClose={() => setEditing(null)} maxWidth={520} ariaLabel={editing === "new" ? t("actions.addSignature") : t("actions.editSignature")}><div className="space-y-4 p-5"><h2 className="text-base font-bold">{editing === "new" ? t("actions.addSignature") : t("actions.editSignature")}</h2><Input label={t("fields.signatureName")} value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} data-modal-autofocus /><Textarea label={t("fields.signatureContent")} value={form.content} onChange={(event) => setForm((current) => ({ ...current, content: event.target.value }))} rows={7} /><div className="flex justify-end gap-2"><Button onClick={() => setEditing(null)}>{t("common.cancel")}</Button><Button variant="primary" disabled={!form.name.trim() || !form.content.trim()} onClick={saveSignature}>{t("common.save")}</Button></div></div></Modal> : null}
    {deleting ? <ConfirmDialog tone="destructive" title={t("confirm.deleteSignature")} confirmLabel={t("common.delete")} description={deleting.name} onCancel={() => setDeleting(null)} onConfirm={() => { const remaining = compose.signatures.filter((item) => item.id !== deleting.id); updateSection("compose", { signatures: remaining, defaultSignatureId: compose.defaultSignatureId === deleting.id ? remaining[0]?.id ?? "" : compose.defaultSignatureId }); setDeleting(null); }} /> : null}
  </>;
}

export function InboxSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, updateSection, replaceSection } = useSettings(); const value = draft.inbox;
  const tr = (key: string) => t(key as never);
  const select = <K extends keyof typeof value>(key: K, options: string[]) => <Select label={tr(`fields.${String(key)}`)} value={String(value[key])} onChange={(next) => updateSection("inbox", { [key]: next } as Partial<typeof value>)} options={options.map((item) => ({ value: item, label: tr(`options.${String(key)}.${item}`) }))} />;
  return <><SettingsPageIntro title={t("nav.inbox-display")} description={t("descriptions.inbox")} /><SettingsPanel title={t("sections.inboxLayout")}><SettingRow title={t("fields.density")}>{select("density", ["comfortable","compact"])}</SettingRow><SettingRow title={t("fields.previewPane")}>{select("previewPane", ["right","bottom","off"])}</SettingRow><SwitchRow title={t("fields.conversationView")} value={value.conversationView} onChange={(conversationView) => updateSection("inbox", { conversationView })} /><SettingRow title={t("fields.markRead")}>{select("markRead", ["immediate","2seconds","manual"])}</SettingRow><SettingRow title={t("fields.remoteImages")}>{select("remoteImages", ["always","contacts","never"])}</SettingRow><SettingRow title={t("fields.pageSize")}>{select("pageSize", ["25","50","100"])}</SettingRow><SettingRow title={t("fields.mailDateFormat")}><Select label={t("fields.mailDateFormat")} value={value.dateFormat} onChange={(dateFormat) => updateSection("inbox", { dateFormat: dateFormat as typeof value.dateFormat })} options={["relative","short","full"].map((item) => ({ value: item, label: t(`options.mailDateFormat.${item}` as never) }))} /></SettingRow><SettingRow title={t("fields.unreadStyle")}>{select("unreadStyle", ["bold","highlight","dot"])}</SettingRow><section aria-label={t("common.preview")} className={`grid overflow-hidden rounded-(--radius-app) border border-(--border-app) ${value.previewPane === "right" ? "sm:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]" : "grid-cols-1"}`}><div className={`border-(--border-app) ${value.previewPane === "right" ? "sm:border-r" : value.previewPane === "bottom" ? "border-b" : ""}`}><div className={`border-b border-(--border-app) px-4 ${value.density === "compact" ? "py-2" : "py-4"} ${value.unreadStyle === "highlight" ? "bg-(--color-primary)/8" : "bg-(--surface-app)"}`}><p className={value.unreadStyle === "bold" ? "font-bold" : "font-medium"}>{value.unreadStyle === "dot" ? "● " : ""}{t("preview.unreadSubject")}</p><p className="mt-1 truncate text-xs text-(--text-muted)">{t("preview.unreadBody")}</p></div>{value.conversationView ? <p className="px-4 py-2 text-xs text-(--text-muted)">{t("preview.conversationCount", { count: 3 })}</p> : null}</div>{value.previewPane !== "off" ? <div className="min-h-24 bg-(--surface-app) p-4"><p className="text-xs font-semibold text-(--text-muted)">{t("common.preview")}</p><p className="mt-2 text-sm">{t("preview.unreadBody")}</p></div> : null}</section></SettingsPanel><SettingsSaveBar onReset={() => replaceSection("inbox", structuredClone(DEFAULT_USER_SETTINGS.inbox))} /></>;
}

export function SendingSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, updateSection, replaceSection } = useSettings(); const value = draft.sending;
  const tr = (key: string) => t(key as never);
  const select = <K extends keyof typeof value>(key: K, options: string[]) => <Select label={tr(`fields.${String(key)}`)} value={String(value[key])} onChange={(next) => updateSection("sending", { [key]: next } as Partial<typeof value>)} options={options.map((item) => ({ value: item, label: tr(`options.${String(key)}.${item}`) }))} />;
  return <><SettingsPageIntro title={t("nav.sending")} description={t("descriptions.sending")} /><SettingsPanel title={t("sections.replyDefaults")}><SettingRow title={t("fields.defaultReply")}>{select("defaultReply", ["reply","replyAll"])}</SettingRow><SettingRow title={t("fields.quoteStyle")}>{select("quoteStyle", ["inline","below","none"])}</SettingRow><SwitchRow title={t("fields.requestReceipt")} value={value.requestReceipt} onChange={(requestReceipt) => updateSection("sending", { requestReceipt })} /><SettingRow title={t("fields.scheduleDefault")}>{select("scheduleDefault", ["off","nextMorning","custom"])}</SettingRow><SettingRow title={t("fields.autosaveSeconds")}>{select("autosaveSeconds", ["15","30","60"])}</SettingRow><SettingRow title={t("fields.composeMode")}>{select("composeMode", ["html","plain"])}</SettingRow><SettingRow title={t("fields.defaultCc")}><Input type="email" aria-label={t("fields.defaultCc")} value={value.defaultCc} onChange={(event) => updateSection("sending", { defaultCc: event.target.value })} /></SettingRow><SettingRow title={t("fields.defaultBcc")}><Input type="email" aria-label={t("fields.defaultBcc")} value={value.defaultBcc} onChange={(event) => updateSection("sending", { defaultBcc: event.target.value })} /></SettingRow></SettingsPanel><SettingsSaveBar onReset={() => replaceSection("sending", structuredClone(DEFAULT_USER_SETTINGS.sending))} /></>;
}

export function AwaySettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, updateSection, replaceSection } = useSettings(); const value = draft.away; const invalid = Boolean(value.startDate && value.endDate && value.startDate > value.endDate);
  return <><SettingsPageIntro title={t("nav.away")} description={t("descriptions.away")} /><SettingsPanel title={t("sections.awaySchedule")}><SwitchRow title={t("fields.awayEnabled")} value={value.enabled} onChange={(enabled) => updateSection("away", { enabled })} /><div className="grid gap-4 sm:grid-cols-2"><Input type="date" label={t("fields.startDate")} value={value.startDate} onChange={(event) => updateSection("away", { startDate: event.target.value })} error={invalid ? t("errors.dateRange") : undefined} /><Input type="date" label={t("fields.endDate")} value={value.endDate} onChange={(event) => updateSection("away", { endDate: event.target.value })} /></div><Input label={t("fields.subject")} value={value.subject} onChange={(event) => updateSection("away", { subject: event.target.value })} /><Textarea label={t("fields.internalMessage")} value={value.internalMessage} onChange={(event) => updateSection("away", { internalMessage: event.target.value })} /><Textarea label={t("fields.externalMessage")} value={value.externalMessage} onChange={(event) => updateSection("away", { externalMessage: event.target.value })} /><SwitchRow title={t("fields.contactsOnly")} value={value.contactsOnly} onChange={(contactsOnly) => updateSection("away", { contactsOnly })} />{value.enabled ? <div className="rounded-(--radius-app) bg-(--status-success-bg) p-4 text-sm text-(--status-success)"><strong>{value.subject || t("nav.away")}</strong><p className="mt-1 whitespace-pre-wrap text-xs">{value.internalMessage}</p></div> : null}</SettingsPanel><SettingsSaveBar saveDisabled={invalid} onReset={() => replaceSection("away", structuredClone(DEFAULT_USER_SETTINGS.away))} /></>;
}

export function NotificationSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, updateSection, replaceSection } = useSettings(); const value = draft.notifications; const toast = useToast();
  const modeOptions = ["instant","digest","off"].map((item) => ({ value: item, label: t(`options.notificationMode.${item}`) }));
  return <>
    <SettingsPageIntro title={t("nav.notifications")} description={t("descriptions.notifications")} actions={<Button size="sm" onClick={() => toast.info(t("toast.testNotification"))}>{t("actions.testNotification")}</Button>} />
    <SettingsPanel title={t("sections.notificationChannels")}><SwitchRow title={t("fields.browserNotifications")} value={value.browser} onChange={(browser) => updateSection("notifications", { browser })} /><SwitchRow title={t("fields.emailNotifications")} value={value.email} onChange={(email) => updateSection("notifications", { email })} /><SwitchRow title={t("fields.notificationSound")} value={value.sound} onChange={(sound) => updateSection("notifications", { sound })} /></SettingsPanel>
    <SettingsPanel title={t("sections.notificationRules")}>{(Object.keys(value.modes) as Array<keyof typeof value.modes>).map((key) => <SettingRow key={key} title={t(`notificationTypes.${key}`)}><Select label={t(`notificationTypes.${key}`)} value={value.modes[key]} options={modeOptions} onChange={(mode) => updateSection("notifications", { modes: { ...value.modes, [key]: mode } as typeof value.modes })} /></SettingRow>)}</SettingsPanel>
    <SettingsPanel title={t("sections.quietHours")}><div className="grid gap-4 sm:grid-cols-2"><Input type="time" label={t("fields.quietStart")} value={value.quietStart} onChange={(event) => updateSection("notifications", { quietStart: event.target.value })} /><Input type="time" label={t("fields.quietEnd")} value={value.quietEnd} onChange={(event) => updateSection("notifications", { quietEnd: event.target.value })} /></div><SwitchRow title={t("fields.weekendNotifications")} value={value.weekends} onChange={(weekends) => updateSection("notifications", { weekends })} /></SettingsPanel>
    <SettingsSaveBar onReset={() => replaceSection("notifications", structuredClone(DEFAULT_USER_SETTINGS.notifications))} />
  </>;
}
