"use client";

import { useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { Link } from "@/i18n/navigation";
import { ArrowDown, ArrowUp, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { useSettings } from "@/context/settings-context";
import { useMail } from "@/context/mail-context";
import { useToast } from "@/context/toast-context";
import { DEFAULT_USER_SETTINGS } from "@/lib/user-settings";
import type { Email } from "@/types/mail";
import type { FilterAction, FilterField, FilterSetting, LabelSetting } from "@/types/user-settings";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Dropdown, type DropdownOption } from "@/components/ui/Dropdown";
import { Input } from "@/components/ui/Input";
import { SegmentedControl } from "@/components/ui/SegmentedControl";
import { Switch } from "@/components/ui/Switch";
import { ConfirmDialog } from "@/components/overlay/ConfirmDialog";
import { Modal } from "@/components/overlay/Modal";
import { SettingsPageIntro, SettingsPanel, SettingsSaveBar, SettingRow, SwitchRow } from "./SettingsPrimitives";

const LABEL_COLORS = ["#2b4bf2", "#2e8b5b", "#e0ac4a", "#6b5ca8", "#c0433b"];
function Select({ value, onChange, options, label }: { value: string; onChange: (value: string) => void; options: DropdownOption[]; label: string }) { return <Dropdown value={value} onChange={onChange} options={options} variant="form" label={label} />; }

export function LabelsSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, replaceSection } = useSettings(); const toast = useToast();
  const [editing, setEditing] = useState<LabelSetting | "new" | null>(null); const [form, setForm] = useState({ name: "", color: LABEL_COLORS[0] }); const [deleting, setDeleting] = useState<LabelSetting | null>(null); const [error, setError] = useState("");
  const open = (item?: LabelSetting) => { setEditing(item ?? "new"); setForm(item ? { name: item.name, color: item.color } : { name: "", color: LABEL_COLORS[0] }); setError(""); };
  const save = () => { const name = form.name.trim(); if (!name) return; if (draft.labels.some((item) => item.name.toLocaleLowerCase() === name.toLocaleLowerCase() && (editing === "new" || (editing !== null && item.id !== editing.id)))) { setError(t("errors.duplicateLabel")); return; } const next = editing === "new" ? [...draft.labels, { id: `label-${Date.now()}`, name, color: form.color, count: 0, visible: true }] : draft.labels.map((item) => item.id === editing?.id ? { ...item, name, color: form.color } : item); replaceSection("labels", next); setEditing(null); };
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= draft.labels.length) return; const next = [...draft.labels]; [next[index], next[target]] = [next[target], next[index]]; replaceSection("labels", next); };
  return <><SettingsPageIntro title={t("nav.labels")} description={t("descriptions.labels")} actions={<Button variant="primary" size="sm" leadingIcon={<Plus size={15} />} onClick={() => open()}>{t("actions.addLabel")}</Button>} /><SettingsPanel title={t("sections.labels")}>{draft.labels.map((item, index) => <article key={item.id} className="grid min-w-0 gap-2 rounded-(--radius-app) border border-(--border-app) p-3">
    <div className="flex min-w-0 items-start gap-2"><span className="mt-1 size-3 shrink-0 rounded-full" style={{ background: item.color }} /><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{item.name}</h3><p className="text-xs text-(--text-muted)">{t("common.messageCount", { count: item.count })}</p></div><Switch on={item.visible} onToggle={() => replaceSection("labels", draft.labels.map((label) => label.id === item.id ? { ...label, visible: !label.visible } : label))} label={`${item.name}: ${t("fields.labelVisible")}`} size="sm" /></div>
    <div className="flex flex-wrap items-center justify-end gap-1 border-t border-(--border-app) pt-2"><Button size="icon" variant="ghost" className="size-8" aria-label={`${item.name}: ${t("actions.moveUp")}`} disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp size={14} /></Button><Button size="icon" variant="ghost" className="size-8" aria-label={`${item.name}: ${t("actions.moveDown")}`} disabled={index === draft.labels.length - 1} onClick={() => move(index, 1)}><ArrowDown size={14} /></Button><Button size="sm" variant="ghost" aria-label={`${item.name}: ${t("common.edit")}`} onClick={() => open(item)}>{t("common.edit")}</Button><Button size="icon" variant="ghost" className="size-8 text-(--status-danger)" aria-label={`${item.name}: ${t("common.delete")}`} onClick={() => setDeleting(item)}><Trash2 size={14} /></Button></div>
  </article>)}</SettingsPanel><SettingsSaveBar onReset={() => replaceSection("labels", structuredClone(DEFAULT_USER_SETTINGS.labels))} />
    {editing ? <Modal onClose={() => setEditing(null)} maxWidth={420} ariaLabel={editing === "new" ? t("actions.addLabel") : t("actions.editLabel")}><div className="space-y-4 p-5"><h2 className="text-base font-bold">{editing === "new" ? t("actions.addLabel") : t("actions.editLabel")}</h2><Input label={t("fields.labelName")} value={form.name} onChange={(event) => { setForm((current) => ({ ...current, name: event.target.value })); setError(""); }} error={error} data-modal-autofocus /><fieldset><legend className="mb-2 text-sm font-medium">{t("fields.labelColor")}</legend><div className="flex gap-2">{LABEL_COLORS.map((color) => <Button key={color} size="icon" variant="ghost" aria-label={color} aria-pressed={form.color === color} className="size-9 rounded-full p-0 focus-visible:ring-3 focus-visible:ring-(--focus-ring)" style={{ background: color, boxShadow: form.color === color ? "0 0 0 2px var(--surface-app), 0 0 0 4px currentColor" : undefined, color }} onClick={() => setForm((current) => ({ ...current, color }))} />)}</div></fieldset><div className="flex justify-end gap-2"><Button onClick={() => setEditing(null)}>{t("common.cancel")}</Button><Button variant="primary" disabled={!form.name.trim()} onClick={save}>{t("common.save")}</Button></div></div></Modal> : null}
    {deleting ? <ConfirmDialog tone="destructive" title={t("confirm.deleteLabel")} confirmLabel={t("common.delete")} description={deleting.name} onCancel={() => setDeleting(null)} onConfirm={() => { const item = deleting; const index = draft.labels.findIndex((label) => label.id === item.id); replaceSection("labels", draft.labels.filter((label) => label.id !== item.id)); setDeleting(null); toast.undo(t("toast.labelDeleted"), () => { const next = [...draft.labels.filter((label) => label.id !== item.id)]; next.splice(index, 0, item); replaceSection("labels", next); }); }} /> : null}
  </>;
}

const EMPTY_FILTER: Omit<FilterSetting, "id"> = { name: "", enabled: true, field: "from", value: "", action: "move", actionValue: "Inbox" };
function countMatchingMockEmails(filter: FilterSetting, emails: Email[]) {
  const needle = filter.value.trim().toLocaleLowerCase();
  if (!needle) return 0;
  return emails.filter((mail) => {
    const text = filter.field === "from" ? `${mail.from.name} ${mail.from.email}`
      : filter.field === "to" ? mail.to.join(" ")
      : filter.field === "subject" ? mail.subject
      : filter.field === "body" ? `${mail.preview} ${mail.body.join(" ")}`
      : ""; // The sample mail model has no attachment or size metadata.
    return text.toLocaleLowerCase().includes(needle);
  }).length;
}
export function FiltersSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, replaceSection } = useSettings(); const toast = useToast();
  const { emails } = useMail();
  const [editing, setEditing] = useState<FilterSetting | "new" | null>(null); const [form, setForm] = useState<Omit<FilterSetting, "id">>(EMPTY_FILTER); const [deleting, setDeleting] = useState<FilterSetting | null>(null);
  const open = (item?: FilterSetting) => { setEditing(item ?? "new"); setForm(item ? { name: item.name, enabled: item.enabled, field: item.field, value: item.value, action: item.action, actionValue: item.actionValue } : EMPTY_FILTER); };
  const save = () => { if (!form.name.trim() || !form.value.trim()) return; const next = editing === "new" ? [...draft.filters, { ...form, id: `filter-${Date.now()}` }] : draft.filters.map((item) => item.id === editing?.id ? { ...item, ...form } : item); replaceSection("filters", next); setEditing(null); };
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= draft.filters.length) return; const next = [...draft.filters]; [next[index], next[target]] = [next[target], next[index]]; replaceSection("filters", next); };
  return <><SettingsPageIntro title={t("nav.filters")} description={t("descriptions.filters")} actions={<Button variant="primary" size="sm" leadingIcon={<Plus size={15} />} onClick={() => open()}>{t("actions.addFilter")}</Button>} /><SettingsPanel title={t("sections.filters")}>{draft.filters.map((item, index) => <article key={item.id} className="grid min-w-0 gap-2 rounded-(--radius-app) border border-(--border-app) p-3">
    <div className="flex min-w-0 items-start gap-2"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-(--surface-muted) text-xs font-bold">{index + 1}</span><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{item.name}</h3><p className="break-words text-xs text-(--text-muted)">{t(`options.filterField.${item.field}`)}: {item.value} → {t(`options.filterAction.${item.action}`)}{item.actionValue ? ` · ${item.actionValue}` : ""}</p></div><Switch on={item.enabled} onToggle={() => replaceSection("filters", draft.filters.map((filter) => filter.id === item.id ? { ...filter, enabled: !filter.enabled } : filter))} label={`${item.name}: ${t("fields.filterEnabled")}`} size="sm" /></div>
    <div className="flex flex-wrap items-center justify-end gap-1 border-t border-(--border-app) pt-2"><Button size="icon" variant="ghost" className="size-8" aria-label={`${item.name}: ${t("actions.moveUp")}`} disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp size={14} /></Button><Button size="icon" variant="ghost" className="size-8" aria-label={`${item.name}: ${t("actions.moveDown")}`} disabled={index === draft.filters.length - 1} onClick={() => move(index, 1)}><ArrowDown size={14} /></Button><Button size="sm" variant="ghost" aria-label={`${item.name}: ${t("actions.test")}`} onClick={() => toast.info(t("common.messageCount", { count: countMatchingMockEmails(item, emails) }), { sub: item.name })}>{t("actions.test")}</Button><Button size="sm" variant="ghost" aria-label={`${item.name}: ${t("common.edit")}`} onClick={() => open(item)}>{t("common.edit")}</Button><Button size="icon" variant="ghost" className="size-8 text-(--status-danger)" aria-label={`${item.name}: ${t("common.delete")}`} onClick={() => setDeleting(item)}><Trash2 size={14} /></Button></div>
  </article>)}</SettingsPanel><SettingsSaveBar onReset={() => replaceSection("filters", structuredClone(DEFAULT_USER_SETTINGS.filters))} />
    {editing ? <Modal onClose={() => setEditing(null)} maxWidth={520} ariaLabel={editing === "new" ? t("actions.addFilter") : t("actions.editFilter")} overflowVisible><div className="space-y-4 p-5"><h2 className="text-base font-bold">{editing === "new" ? t("actions.addFilter") : t("actions.editFilter")}</h2><Input label={t("fields.filterName")} value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} data-modal-autofocus /><div className="grid gap-3 sm:grid-cols-2"><Select label={t("fields.condition")} value={form.field} onChange={(field) => setForm((current) => ({ ...current, field: field as FilterField }))} options={["from","to","subject","body","attachment","size"].map((value) => ({ value, label: t(`options.filterField.${value}`) }))} /><Input label={t("fields.conditionValue")} value={form.value} onChange={(event) => setForm((current) => ({ ...current, value: event.target.value }))} /></div><div className="grid gap-3 sm:grid-cols-2"><Select label={t("fields.action")} value={form.action} onChange={(action) => setForm((current) => ({ ...current, action: action as FilterAction }))} options={["move","label","star","read","forward","delete"].map((value) => ({ value, label: t(`options.filterAction.${value}`) }))} /><Input label={t("fields.actionValue")} value={form.actionValue} onChange={(event) => setForm((current) => ({ ...current, actionValue: event.target.value }))} /></div><div className="flex justify-end gap-2"><Button onClick={() => setEditing(null)}>{t("common.cancel")}</Button><Button variant="primary" disabled={!form.name.trim() || !form.value.trim()} onClick={save}>{t("common.save")}</Button></div></div></Modal> : null}
    {deleting ? <ConfirmDialog tone="destructive" title={t("confirm.deleteFilter")} confirmLabel={t("common.delete")} description={deleting.name} onCancel={() => setDeleting(null)} onConfirm={() => { replaceSection("filters", draft.filters.filter((item) => item.id !== deleting.id)); setDeleting(null); toast.success(t("toast.filterDeleted")); }} /> : null}
  </>;
}

export function BlockedSendersSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, replaceSection } = useSettings(); const toast = useToast(); const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState<"all" | "email" | "domain">("all"); const [value, setValue] = useState(""); const [error, setError] = useState(""); const [deleting, setDeleting] = useState<string | null>(null);
  const filtered = useMemo(() => draft.blockedSenders.filter((item) => (typeFilter === "all" || item.type === typeFilter) && item.value.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [draft.blockedSenders, query, typeFilter]);
  const add = () => { const clean = value.trim().toLocaleLowerCase().replace(/^@/, ""); if (!clean || (!clean.includes(".") && !clean.includes("@"))) { setError(t("errors.invalidSender")); return; } if (draft.blockedSenders.some((item) => item.value === clean)) { setError(t("errors.duplicateSender")); return; } replaceSection("blockedSenders", [...draft.blockedSenders, { id: `blocked-${Date.now()}`, value: clean, type: clean.includes("@") ? "email" : "domain" }]); setValue(""); setError(""); toast.success(t("toast.senderBlocked"), { sub: clean }); };
  return <><SettingsPageIntro title={t("nav.blocked-senders")} description={t("descriptions.blockedSenders")} /><SettingsPanel title={t("sections.blockedSenders")}><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><Input label={t("fields.senderOrDomain")} value={value} onChange={(event) => { setValue(event.target.value); setError(""); }} error={error} onKeyDown={(event) => { if (event.key === "Enter") add(); }} /><Button variant="primary" className="self-end" onClick={add}>{t("actions.block")}</Button></div><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><Input leadingIcon={<Search size={16} />} placeholder={t("actions.search")} aria-label={t("actions.search")} value={query} onChange={(event) => setQuery(event.target.value)} /><SegmentedControl label={t("sections.blockedSenders")} value={typeFilter} onChange={setTypeFilter} options={[{ value: "all", label: t("common.all") }, { value: "email", label: t("options.senderType.email") }, { value: "domain", label: t("options.senderType.domain") }]} /></div>{filtered.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-(--radius-app) border border-(--border-app) p-3"><Badge>{t(`options.senderType.${item.type}`)}</Badge><span className="min-w-0 flex-1 break-words text-sm">{item.value}</span><Button size="sm" variant="ghost" className="text-(--status-danger)" aria-label={`${item.value}: ${t("actions.unblock")}`} onClick={() => setDeleting(item.id)}>{t("actions.unblock")}</Button></div>)}</SettingsPanel><SettingsSaveBar onReset={() => replaceSection("blockedSenders", structuredClone(DEFAULT_USER_SETTINGS.blockedSenders))} />{deleting ? <ConfirmDialog tone="destructive" title={t("confirm.unblockSender")} confirmLabel={t("actions.unblock")} description={draft.blockedSenders.find((item) => item.id === deleting)?.value} onCancel={() => setDeleting(null)} onConfirm={() => { const blocked = draft.blockedSenders.find((item) => item.id === deleting)?.value; replaceSection("blockedSenders", draft.blockedSenders.filter((item) => item.id !== deleting)); setDeleting(null); toast.success(t("toast.senderUnblocked"), { sub: blocked }); }} /> : null}</>;
}

export function AccountSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, updateSection, replaceSection } = useSettings(); const toast = useToast(); const [alias, setAlias] = useState(""); const [error, setError] = useState(""); const [deletingAlias, setDeletingAlias] = useState<string | null>(null);
  const account = draft.account; const addAlias = () => { const clean = alias.trim().toLocaleLowerCase(); if (!/^\S+@\S+\.\S+$/.test(clean)) { setError(t("errors.invalidEmail")); return; } if ([account.primaryEmail, ...account.aliases].includes(clean)) { setError(t("errors.duplicateAlias")); return; } updateSection("account", { aliases: [...account.aliases, clean] }); setAlias(""); setError(""); };
  const invalidName = !account.displayName.trim();
  const invalidReplyTo = !/^\S+@\S+\.\S+$/.test(account.replyTo.trim());
  return <><SettingsPageIntro title={t("nav.account")} description={t("descriptions.account")} /><SettingsPanel title={t("sections.accountIdentity")}><SettingRow title={t("fields.displayName")}><Input aria-label={t("fields.displayName")} value={account.displayName} error={invalidName ? t("errors.requiredName") : undefined} onChange={(event) => updateSection("account", { displayName: event.target.value })} /></SettingRow><SettingRow title={t("fields.primaryEmail")}><Input aria-label={t("fields.primaryEmail")} value={account.primaryEmail} disabled /></SettingRow><SettingRow title={t("fields.replyTo")}><Input type="email" aria-label={t("fields.replyTo")} value={account.replyTo} error={invalidReplyTo ? t("errors.invalidEmail") : undefined} onChange={(event) => updateSection("account", { replyTo: event.target.value })} /></SettingRow></SettingsPanel><SettingsPanel title={t("sections.aliases")}><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><Input type="email" label={t("fields.newAlias")} value={alias} error={error} onChange={(event) => { setAlias(event.target.value); setError(""); }} /><Button variant="primary" className="self-end" onClick={addAlias}>{t("actions.add")}</Button></div>{account.aliases.map((item) => <div key={item} className="flex items-center gap-3 rounded-(--radius-app) border border-(--border-app) p-3"><span className="min-w-0 flex-1 break-words text-sm">{item}</span><Button size="sm" variant="ghost" className="text-(--status-danger)" aria-label={`${item}: ${t("common.delete")}`} onClick={() => setDeletingAlias(item)}>{t("common.delete")}</Button></div>)}</SettingsPanel><SettingsSaveBar saveDisabled={invalidName || invalidReplyTo} onReset={() => replaceSection("account", structuredClone(DEFAULT_USER_SETTINGS.account))} />{deletingAlias ? <ConfirmDialog tone="destructive" title={t("confirm.deleteAlias")} confirmLabel={t("common.delete")} description={deletingAlias} onCancel={() => setDeletingAlias(null)} onConfirm={() => { updateSection("account", { aliases: account.aliases.filter((item) => item !== deletingAlias) }); toast.success(t("toast.aliasDeleted"), { sub: deletingAlias }); setDeletingAlias(null); }} /> : null}</>;
}

export function SecuritySettingsView() {
  const t = useTranslations("settingsSystem");
  const locale = useLocale();
  const { draft, hydrated, updateSection, replaceSection } = useSettings();
  const toast = useToast();
  const [confirm, setConfirm] = useState<{ kind: "codes" | "all" | "session"; id?: string } | null>(null);
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [passwords, setPasswords] = useState({ current: "", next: "", confirm: "" });
  const [passwordError, setPasswordError] = useState("");
  const value = draft.security;
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: draft.locale.timezone }), [draft.locale.timezone, locale]);
  const formatDate = (date: string) => hydrated && !Number.isNaN(Date.parse(date)) ? dateFormatter.format(new Date(date)) : "—";
  const runConfirm = () => { if (!confirm) return; if (confirm.kind === "codes") { updateSection("security", { backupCodes: 10 }); toast.success(t("toast.codesRegenerated")); } else if (confirm.kind === "all") { updateSection("security", { sessions: value.sessions.filter((item) => item.current) }); toast.success(t("toast.sessionsRevoked")); } else { updateSection("security", { sessions: value.sessions.filter((item) => item.id !== confirm.id) }); toast.success(t("toast.sessionRevoked")); } setConfirm(null); };
  const submitPassword = () => {
    if (!passwords.current) { setPasswordError(t("errors.passwordRequired")); return; }
    if (passwords.next.length < 8) { setPasswordError(t("errors.passwordLength")); return; }
    if (passwords.next !== passwords.confirm) { setPasswordError(t("errors.passwordMismatch")); return; }
    updateSection("security", { passwordChangedAt: new Date().toISOString() });
    setPasswords({ current: "", next: "", confirm: "" });
    setPasswordError("");
    setPasswordOpen(false);
    toast.success(t("toast.passwordChanged"));
  };
  return <>
    <SettingsPageIntro title={t("nav.security")} description={t("descriptions.security")} />
    <SettingsPanel title={t("sections.authentication")}>
      <SwitchRow title={t("fields.twoFactor")} description={t("descriptions.twoFactor")} value={value.twoFactor} onChange={(twoFactor) => updateSection("security", { twoFactor })} />
      <SettingRow title={t("fields.backupCodes")} description={t("common.remainingCount", { count: value.backupCodes })}><Button size="sm" onClick={() => setConfirm({ kind: "codes" })}>{t("actions.regenerate")}</Button></SettingRow>
      <SettingRow title={t("fields.password")} description={t("common.passwordChanged", { value: formatDate(value.passwordChangedAt) })}><Button size="sm" onClick={() => setPasswordOpen(true)}>{t("actions.changePassword")}</Button></SettingRow>
    </SettingsPanel>
    <SettingsPanel title={t("sections.sessions")} actions={<Button size="sm" variant="danger" disabled={value.sessions.every((item) => item.current)} onClick={() => setConfirm({ kind: "all" })}>{t("actions.logoutOthers")}</Button>}>
      {value.sessions.map((session) => <article key={session.id} className="flex items-center gap-3 rounded-(--radius-app) border border-(--border-app) p-3"><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{session.device}</h3><p className="text-xs text-(--text-muted)">{session.location} · {t("common.lastActive", { value: formatDate(session.lastActive) })}</p></div>{session.current ? <Badge tone="success">{t("common.current")}</Badge> : <Button size="sm" variant="ghost" className="text-(--status-danger)" onClick={() => setConfirm({ kind: "session", id: session.id })}>{t("actions.logout")}</Button>}</article>)}
    </SettingsPanel>
    <SettingsSaveBar onReset={() => replaceSection("security", structuredClone(DEFAULT_USER_SETTINGS.security))} />
    {passwordOpen ? <Modal onClose={() => { setPasswordOpen(false); setPasswordError(""); }} maxWidth={440} ariaLabel={t("actions.changePassword")}><form className="space-y-4 p-5" onSubmit={(event) => { event.preventDefault(); submitPassword(); }}><h2 className="text-base font-bold">{t("actions.changePassword")}</h2><Input type="password" label={t("fields.currentPassword")} value={passwords.current} onChange={(event) => { setPasswords((current) => ({ ...current, current: event.target.value })); setPasswordError(""); }} data-modal-autofocus /><Input type="password" label={t("fields.newPassword")} value={passwords.next} onChange={(event) => { setPasswords((current) => ({ ...current, next: event.target.value })); setPasswordError(""); }} /><Input type="password" label={t("fields.confirmPassword")} value={passwords.confirm} error={passwordError} onChange={(event) => { setPasswords((current) => ({ ...current, confirm: event.target.value })); setPasswordError(""); }} /><div className="flex justify-end gap-2"><Button type="button" onClick={() => setPasswordOpen(false)}>{t("common.cancel")}</Button><Button type="submit" variant="primary">{t("actions.changePassword")}</Button></div></form></Modal> : null}
    {confirm ? <ConfirmDialog tone={confirm.kind === "codes" ? "warning" : "destructive"} title={t(`confirm.${confirm.kind}`)} confirmLabel={t(confirm.kind === "codes" ? "actions.regenerate" : confirm.kind === "all" ? "actions.logoutOthers" : "actions.logout")} onCancel={() => setConfirm(null)} onConfirm={runConfirm} /> : null}
  </>;
}

export function IntegrationsSettingsView() {
  const t = useTranslations("settingsSystem"); const locale = useLocale(); const { draft, hydrated, replaceSection } = useSettings(); const toast = useToast(); const [details, setDetails] = useState<string | null>(null); const [disconnecting, setDisconnecting] = useState<string | null>(null);
  const update = (id: string, patch: Partial<(typeof draft.integrations)[number]>) => replaceSection("integrations", draft.integrations.map((item) => item.id === id ? { ...item, ...patch } : item));
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: draft.locale.timezone }), [draft.locale.timezone, locale]);
  const name = (id: string) => t(`integrations.names.${id}`);
  const scope = (id: string) => t(`integrations.scopes.${id}`);
  const lastSync = (value: string) => hydrated && !Number.isNaN(Date.parse(value)) ? dateFormatter.format(new Date(value)) : "—";
  const detail = draft.integrations.find((item) => item.id === details);
  return <><SettingsPageIntro title={t("nav.integrations")} description={t("descriptions.integrations")} /><SettingsPanel title={t("sections.integrations")}>{draft.integrations.map((item) => <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-(--radius-app) border border-(--border-app) p-4"><div className="min-w-48 flex-1"><div className="flex items-center gap-2"><h3 className="text-sm font-semibold">{name(item.id)}</h3><Badge tone={!item.connected ? "neutral" : item.status === "error" ? "danger" : "success"}>{t(!item.connected ? "common.disconnected" : item.status === "error" ? "common.syncFailed" : "common.connected")}</Badge></div><p className="mt-1 text-xs text-(--text-muted)">{scope(item.id)}</p><p className="mt-1 text-[11px] text-(--text-muted)">{item.lastSync ? t("common.lastSync", { value: lastSync(item.lastSync) }) : t("common.neverSynced")}</p></div>{item.connected ? <><Button size="sm" variant="ghost" leadingIcon={<RefreshCw size={14} />} aria-label={`${name(item.id)}: ${t("actions.sync")}`} onClick={() => { update(item.id, { lastSync: new Date().toISOString(), status: "ok" }); toast.success(t("toast.syncComplete"), { sub: name(item.id) }); }}>{t("actions.sync")}</Button><Button size="sm" aria-label={`${name(item.id)}: ${t("common.settings")}`} onClick={() => setDetails(item.id)}>{t("common.settings")}</Button><Button size="sm" variant="ghost" className="text-(--status-danger)" aria-label={`${name(item.id)}: ${t("actions.disconnect")}`} onClick={() => setDisconnecting(item.id)}>{t("actions.disconnect")}</Button></> : <Button size="sm" variant="primary" aria-label={`${name(item.id)}: ${t("actions.connect")}`} onClick={() => { update(item.id, { connected: true, lastSync: new Date().toISOString(), status: "ok" }); toast.success(t("toast.integrationConnected"), { sub: name(item.id) }); }}>{t("actions.connect")}</Button>}</article>)}</SettingsPanel><SettingsSaveBar onReset={() => replaceSection("integrations", structuredClone(DEFAULT_USER_SETTINGS.integrations))} />{detail ? <Modal onClose={() => setDetails(null)} maxWidth={440} ariaLabel={t("common.settings")}><div className="space-y-4 p-5"><h2 className="text-base font-bold">{name(detail.id)}</h2><p className="text-sm text-(--text-muted)">{scope(detail.id)}</p><SwitchRow title={t("fields.autoSync")} value={detail.autoSync} onChange={(autoSync) => update(detail.id, { autoSync })} /><div className="flex justify-end"><Button variant="primary" onClick={() => setDetails(null)}>{t("common.done")}</Button></div></div></Modal> : null}{disconnecting ? <ConfirmDialog tone="destructive" title={t("confirm.disconnect")} confirmLabel={t("actions.disconnect")} description={name(disconnecting)} onCancel={() => setDisconnecting(null)} onConfirm={() => { update(disconnecting, { connected: false, autoSync: false, status: "ok" }); setDisconnecting(null); toast.success(t("toast.integrationDisconnected")); }} /> : null}</>;
}

export function ShortcutsSettingsView() {
  const t = useTranslations("settingsSystem"); const { draft, updateSection, replaceSection } = useSettings(); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const value = draft.shortcuts;
  const entries = Object.entries(value.bindings).filter(([key]) => t(`shortcutActions.${key}`).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const change = (key: string, next: string) => { const clean = next.trim().toUpperCase(); const conflict = Object.entries(value.bindings).find(([otherKey, binding]) => otherKey !== key && binding.toUpperCase() === clean); if (clean && conflict) { setError(t("errors.shortcutConflict", { action: t(`shortcutActions.${conflict[0]}`) })); return; } setError(""); updateSection("shortcuts", { bindings: { ...value.bindings, [key]: clean } }); };
  return <><SettingsPageIntro title={t("nav.shortcuts")} description={t("descriptions.shortcuts")} actions={<Link href="/shortcuts" className="inline-flex min-h-10 items-center rounded-(--radius-app) border border-(--border-app) px-3 text-sm font-semibold hover:bg-(--control-hover)">{t("actions.viewShortcutReference")}</Link>} /><SettingsPanel title={t("sections.shortcuts")}><SwitchRow title={t("fields.shortcutsEnabled")} value={value.enabled} onChange={(enabled) => updateSection("shortcuts", { enabled })} /><Input leadingIcon={<Search size={16} />} placeholder={t("actions.search")} aria-label={t("actions.search")} value={query} onChange={(event) => setQuery(event.target.value)} />{error ? <p role="alert" className="text-xs text-(--status-danger)">{error}</p> : null}{entries.map(([key, binding]) => <SettingRow key={key} title={t(`shortcutActions.${key}`)}><Input aria-label={t(`shortcutActions.${key}`)} value={binding} disabled={!value.enabled} onChange={(event) => change(key, event.target.value)} className="font-mono uppercase" /></SettingRow>)}</SettingsPanel><SettingsSaveBar onReset={() => replaceSection("shortcuts", structuredClone(DEFAULT_USER_SETTINGS.shortcuts))} /></>;
}
